spring.application.name=webflux-docker
server.port=8080
server.compression.enabled=true
server.compression.min-response-size=1024


# Actuator configuration
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
management.metrics.enable.jvm=true

# Logging
logging.level.root=INFO
logging.level.com.webflux_docker=DEBUG
logging.pattern.console=%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n
